name: Katalon API Test

on:
  push:
    branches: [ master ]

jobs:
  katalon-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Katalon Studio
        run: |
          curl -L -o katalon.zip https://download.katalon.com/9.5.0/Katalon_Studio_Windows_64-9.5.0.zip
          tar -xf katalon.zip

      - name: Run Katalon API Test Suite
        shell: cmd
        run: |
          cd Katalon_Studio_Windows_64-9.5.0
          katalonc.exe ^
          -noSplash ^
          -runMode=console ^
          -licenseRelease=true ^
          -apiKey=%KATALON_API_KEY% ^
          -projectPath="Reqres_API_TEST_QA_Engineer_Venturo_RezaParamarta.prj" ^
          -testSuitePath="Test Suites/TS_Reqres_API" ^
          -executionProfile="default" ^
          -browserType="Web Service"
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}
