name: Katalon API Test

on: [push]

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Katalon Runtime Engine
        run: |
          curl -L -o katalon.tar.gz https://download.katalon.com/9.5.0/Katalon_Runtime_Engine_Linux_64-9.5.0.tar.gz
          tar -xzf katalon.tar.gz
          chmod +x katalonc

      - name: Run API Test Suite Collection
        run: |
          ./katalonc \
          -noSplash \
          -runMode=console \
          -licenseRelease=true \
          -apiKey=${{ secrets.KATALON_API_KEY }} \
          -projectPath="$PWD/Reqres_API_TEST_QA_Engineer_Venturo_RezaParamarta.prj" \
          -testSuiteCollectionPath="Test Suite Collections/TSC_Reqres_API" \
          -executionProfile="default"
